export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const FETCH_BOOKMARKS_SUCCESS = 'FETCH_BOOKMARKS_SUCCESS';
export const SAVE_KEYWORDS = 'SAVE_KEYWORDS';
export const SAVE_BOOKMARK = 'SAVE_BOOKMARK';
export const SAVE_BOOKMARK_SUCCESS = 'SAVE_BOOKMARK_SUCCESS';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
